[package]
name = "Gratsch"
version = "0.0.2"
authors = ["Elia Vandini"]
license = "MIT"
description = "A Typst template for homework"
entrypoint = "export.typ"
categories = ["report"]
keywords = ["homework", "template"]
repository = "https://github.com/eliavandini/Gratsch"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
